describe('Visit Note Registration', () => {

  beforeEach(() => {
    cy.login()
    cy.selectLocation()
    cy.language()
    cy.visit('/patient-registration')
    cy.get('#givenName').type(Math.random().toString(36).substring(2, 10))
    cy.get('#familyName').type(Math.random().toString(36).substring(2, 10))
    cy.get(':nth-child(1) > .cds--radio-button__label > .cds--radio-button__appearance').click()
    cy.get(':nth-child(3) > :nth-child(2) > .cds--content-switcher > [tabindex="-1"]').click()
    cy.get('#monthsEstimated').type(1)
    cy.get('.-esm-patient-registration__patient-registration__submitButton___FPRJM').click()
    cy.contains('New Patient Created', { timeout: 15000 })
      .should('be.visible')
    cy.get('button:contains("Start a visit")').then(($btn) => {
      cy.wrap($btn).click({ force: true, multiple: true })
    })
    cy.get('.cds--radio-button__label:contains("Visit")').click()
    cy.get('.cds--form button:contains("Start visit")').click()
    cy.contains('Visit started', { timeout: 15000 })
      .should('be.visible')
    cy.get('.omrs-modals-container', { timeout: 15000 })
      .should('not.be.visible')
    cy.get('button:contains("Visit note")').click()
  })

  it(`Test add a visit with only primary diagnosis`, () => {
    cy.contains('Add a visit note', { timeout: 15000 })
      .should('be.visible')
    cy.get('#primaryDiagnosisSearch').type('Headache')
    cy.get('.-esm-patient-notes__visit-notes-form__diagnosis___czR8d:contains("Headache")').click()
    cy.get('.cds--tag__label:contains("Headache")', { timeout: 15000 }).should('exist')
    cy.get('button:contains("Save and close")').click()
    cy.contains('Visit note saved', { timeout: 15000 })
  })

  it(`Test don't import by image too big on add a visit note`, () => {
    cy.contains('Add a visit note', { timeout: 15000 })
      .should('be.visible')
    cy.get('button').contains('Add image').click()
    cy.get('.cds--file-input').selectFile('cypress/import/LargeImage.jpg', { force: true })
    cy.contains('The file "LargeImage.jpg" exceeds the size limit of 1 MB.')
  })

  it(`Test add a visit with all fields filled`, () => {
    cy.contains('Add a visit note', { timeout: 15000 })
      .should('be.visible')
    cy.get('#primaryDiagnosisSearch').type('Headache')
    cy.get('.-esm-patient-notes__visit-notes-form__diagnosis___czR8d:contains("Headache")').click()
    cy.get('.cds--tag__label:contains("Headache")', { timeout: 15000 }).should('exist')
    cy.get('#secondaryDiagnosisSearch').type('Heartburn')
    cy.get('.-esm-patient-notes__visit-notes-form__diagnosis___czR8d:contains("Heartburn")').click()
    cy.get('.cds--tag__label:contains("Heartburn")', { timeout: 15000 }).should('exist')
    cy.get('#additionalNote').type(Math.random().toString(36).substring(2, 100))
    cy.get('button:contains("Save and close")').click()
    cy.contains('Visit note saved', { timeout: 15000 })
  })
})