language: java
jdk:
 - openjdk6
 - oraclejdk7
script: mvn clean install --batch-mode
matrix:
  allow_failures:
    - jdk: oraclejdk7
branches:
  only:
    - master
notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#openmrs"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
    use_notice: true
    skip_join: true
