name: "OWASP Dependency Check"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  dependencycheck:
    runs-on: ubuntu-latest
    name: dependencycheck_test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build project with Maven
        run: mvn clean install -DskipTests -Dspotbugs.skip=true

      - name: Cache NVD database
        uses: actions/cache@v4
        with:
          path: /github/home/.dependency-check/data
          key: nvd-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            nvd-${{ runner.os }}-

      - name: Run OWASP Dependency-Check (PR)
        if: ${{ github.event_name == 'pull_request' }}
        timeout-minutes: 15
        uses: dependency-check/Dependency-Check_Action@75ba02d6183445fe0761d26e836bde58b1560600
        id: depcheck-without-nvd-key
        env:
          JAVA_HOME: /opt/jdk
        with:
          project: 'openmrs-core'
          path: '.'
          format: 'ALL'
          out: 'reports'
          args: |
            --failOnCVSS 6.2
            --enableRetired
            --disableCentral
            --disableOssIndex
            --suppression dependency-check-suppressions.xml
            --data /github/home/.dependency-check/data

      - name: Run OWASP Dependency-Check (master push)
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        timeout-minutes: 15
        uses: dependency-check/Dependency-Check_Action@75ba02d6183445fe0761d26e836bde58b1560600
        id: depcheck-with-nvd-key
        env:
          JAVA_HOME: /opt/jdk
        with:
          project: 'openmrs-core'
          path: '.'
          format: 'ALL'
          out: 'reports'
          args: |
            --failOnCVSS 6.2
            --enableRetired
            --disableCentral
            --disableOssIndex
            --suppression dependency-check-suppressions.xml
            --data /github/home/.dependency-check/data
            --nvdApiKey ${{ secrets.NVD_API_KEY }}

      - name: Upload Test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Dependency Check report
          path: ${{ github.workspace }}/reports
