name: QaFramework Trigger
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger QAFramework
        uses: peter-evans/repository-dispatch@v1.1.3
        with:
          repository: openmrs/openmrs-contrib-qaframework
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: qa
